version: '3.8'
name: app  # Thêm dòng này

services:
  # Main Application
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage  # Shared storage volume
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
      # Add other environment variables here
    depends_on:
      - redis
    restart: unless-stopped
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  # Celery Worker
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./storage:/app/storage  # Shared storage volume
    environment:
      - REDIS_URL=redis://redis:6379/0
      # Add other environment variables here
    depends_on:
      - redis
    restart: unless-stopped
    command: "celery -A app.worker worker --loglevel=info"
  
  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: "redis-server --appendonly yes"  # Enable persistence

volumes:
  redis-data:  # Persistent volume for Redis data